# Generated by Django 3.1.7 on 2021-04-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20210406_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('resume', models.FileField(upload_to='cnadidates')),
                ('cover_letter', models.TextField(max_length=500)),
            ],
        ),
    ]
