# Generated by Django 3.1.7 on 2021-04-07 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cnadidate', to='job.job'),
            preserve_default=False,
        ),
    ]
